[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lilo-vla"
description = "LiLo-VLA: Compositional Long-Horizon Manipulation via Linked Object-Centric Policies"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}

[tool.setuptools.packages.find]
where = ["."]
include = ["lilo_vla*"]
